<a href="https://colab.research.google.com/github/maheeen-khan/AI_ML_DL_Data-Science/blob/main/Categorical_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('/content/Salaries.csv')
dataset.head()

rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [3]:
dataset['rank'].unique() # check classes in rank column

array(['Prof', 'AssocProf', 'AsstProf'], dtype=object)

###Label Encoding on 'rank' column

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder() # make instance of LabelEncoder object

In [6]:
dataset['rank'] = le.fit_transform(dataset['rank']) # training and applying encoding

In [7]:
dataset['rank'] # check data

0     2
1     2
2     2
3     2
4     2
     ..
73    2
74    0
75    2
76    2
77    2
Name: rank, Length: 78, dtype: int64

In [8]:
dataset['rank'].unique() # after encoding, check unique classes

array([2, 0, 1])

After label encoding:


*    0 assigns to Associate Professor,
*    1 assigns to Assistant Professor,
*    2 assigns to Professor




### One Hot Encoding by Pandas

In [12]:
df = pd.DataFrame(
    {
        "colors" : ["red", "green", "blue", "red", "green", "blue", "red"]
    }
)

df

colors
0    red
1  green
2   blue
3    red
4  green
5   blue
6    red

In [14]:
oneHot = pd.get_dummies(df,columns=['colors'])
oneHot

colors_blue  colors_green  colors_red
0        False         False        True
1        False          True       False
2         True         False       False
3        False         False        True
4        False          True       False
5         True         False       False
6        False         False        True

### One Hot Encoding by Sklearn

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
ohe = OneHotEncoder(sparse_output=False)

In [30]:
arr = ohe.fit_transform(df[['colors']])
arr

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [31]:
pd.DataFrame(arr,columns=['colors_red','colors_green','colors_blue'])

colors_red  colors_green  colors_blue
0         0.0           0.0          1.0
1         0.0           1.0          0.0
2         1.0           0.0          0.0
3         0.0           0.0          1.0
4         0.0           1.0          0.0
5         1.0           0.0          0.0
6         0.0           0.0          1.0

In [33]:
dataset['discipline'].unique() # check classes for apply ordinal encoding

array(['B', 'A'], dtype=object)

### Ordinal Encoding by Sklearn

In [32]:
from sklearn.preprocessing import OrdinalEncoder

In [39]:
oe = OrdinalEncoder(categories=[['A','B']]) # its mean A -> 0 , B -> 1

In [36]:
dataset['discipline'] = oe.fit_transform(dataset[['discipline']])

In [37]:
dataset['discipline'].unique()

array([1., 0.])

In [38]:
dataset['discipline']

0     1.0
1     0.0
2     0.0
3     0.0
4     1.0
     ... 
73    1.0
74    1.0
75    1.0
76    0.0
77    0.0
Name: discipline, Length: 78, dtype: float64